/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.jaas.gui;

import br.com.davidbuzatto.jaas.utils.Constants;
import com.formdev.flatlaf.FlatDarkLaf;
import com.vdurmont.emoji.EmojiParser;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        
        initComponents();
        setTitle( getTitle() + " - " + Constants.VERSION );
        
        JIFDFA jif1 = new JIFDFA( true, null );
        JIFNFA jif2 = new JIFNFA( true );
        JIFENFA jif3 = new JIFENFA( true );
        
        desktopPane.add( jif1 );
        desktopPane.add( jif2 );
        desktopPane.add( jif3 );
        jif1.setVisible( true );
        jif2.setVisible( true );
        jif3.setVisible( true );
        
        setExtendedState( MAXIMIZED_BOTH );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        btnDFA = new javax.swing.JButton();
        btnNFA = new javax.swing.JButton();
        btnENFA = new javax.swing.JButton();
        filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnAbout = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Just Another Automaton Simulator");

        toolbar.setFloatable(false);

        btnDFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jaas/gui/icons/dfaBig.png"))); // NOI18N
        btnDFA.setText("DFA");
        btnDFA.setFocusable(false);
        btnDFA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDFA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFAActionPerformed(evt);
            }
        });
        toolbar.add(btnDFA);

        btnNFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jaas/gui/icons/nfaBig.png"))); // NOI18N
        btnNFA.setText("NFA");
        btnNFA.setFocusable(false);
        btnNFA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNFA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNFAActionPerformed(evt);
            }
        });
        toolbar.add(btnNFA);

        btnENFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jaas/gui/icons/enfaBig.png"))); // NOI18N
        btnENFA.setText("\u03b5NFA");
        btnENFA.setFocusable(false);
        btnENFA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnENFA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnENFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnENFAActionPerformed(evt);
            }
        });
        toolbar.add(btnENFA);
        toolbar.add(filler);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jaas/gui/icons/help.png"))); // NOI18N
        btnAbout.setToolTipText("About");
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        toolbar.add(btnAbout);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFAActionPerformed
        JIFDFA jif = new JIFDFA( true, null );
        desktopPane.add( jif );
        jif.setVisible( true );
    }//GEN-LAST:event_btnDFAActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        JOptionPane.showMessageDialog( this, 
                "Developed by Prof. Dr. David Buzatto\n" + 
                "To help and motivate my dear students! " + 
                EmojiParser.parseToUnicode( ":heart:" ) + "\n" +
                Constants.VERSION, "About...", JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnNFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNFAActionPerformed
        JIFNFA jif = new JIFNFA( true );
        desktopPane.add( jif );
        jif.setVisible( true );
    }//GEN-LAST:event_btnNFAActionPerformed

    private void btnENFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnENFAActionPerformed
        JIFENFA jif = new JIFENFA( true );
        desktopPane.add( jif );
        jif.setVisible( true );
    }//GEN-LAST:event_btnENFAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        
        FlatDarkLaf.install();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible( true );
            }
        } );
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnDFA;
    private javax.swing.JButton btnENFA;
    private javax.swing.JButton btnNFA;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.Box.Filler filler;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
